### ISSUE TITLE
Does not work with multiple sub-projects

### ISSUE THREAD

**Issue by steven-barnes** [sbt-jib/sbt-jib#87] opened 2023-01-04 21:12 UTC
I am in the process of porting our builds to use sbt-jib. The simple projects work fine. Projects with multiple sub-projects fail. What seems to happen is that the settings defined in build.sbt are ignored.

jibBaseImage := "openjdk:11-jre-slim"
jibRegistry := "XXX.dkr.ecr.us-east-1.amazonaws.com"
jibCustomRepositoryPath := Some("repository-name")
jibVersion := version.value
jibJvmFlags := List("-Djib.serialize=true")
jibUseCurrentTimestamp := true

I have tried adding ThisBuild (e.g. ThisBuild / jibBaseImage := "openjdk:11-jre-slim")

I have tried setting the properties on the specific sub-project name (e.g. server / jibBaseImage := "openjdk:11-jre-slim")

The command:

sbt "set ThisBuild / version := \"${VERSION}\"" "set jibTags := List(\"develop\")" clean jibImageBuild

will default to using GraalVM instead of openjdk, and it will attempt to publish the artifact to docker hub, instead of our ECR repository.

**Comment by sideeffffect** [comment] 2023-01-05 02:36
Can you please show us the full (or to the fullest possible extent) sbt configuration?

**Comment by Calquilting** [comment] 2023-01-06 20:42
I have created a basic project that reproduces the problem, and was able to solve 2 of the issues. I could add a multi project example to the README file, if you want.

Sorry for bothering you with a bad bug report. I can build the project with a simple App, but I am still having problems setting the entry point for an Http4s IOApp. If there is a discord or gitter channel I could ask for help there.

**Comment by steven-barnes** [comment] 2023-01-06 20:43
I have created a basic project that reproduces the problem, and was able to solve 2 of the issues. I could add a multi project example to the README file, if you want.

Sorry for bothering you with a bad bug report. I can build the project with a simple App, but I am still having problems setting the entry point for an Http4s IOApp. If there is a discord or gitter channel I could ask for help there.

**Comment by steven-barnes** [comment] 2023-01-07 00:33
OK, I have not resolved the problem. Here is a repo with a simple project containing 3 subproject:

https://github.com/steven-barnes/sbt-jib-test.git

The idea is that only the server project has a deployable artifact. When I try to build it, it seems to want to deploy the common subproject. I have tried setting the jibEntrypoint := None for the subprojects that do not have artifacts.

**Comment by sideeffffect** [comment] 2023-01-10 20:18
Thanks!
I think they key may be to use the task `server/jibImageBuild`
https://github.com/steven-barnes/sbt-jib-test/pull/1

Would that work for you?

**Comment by steven-barnes** [comment] 2023-01-11 17:17
I thought I had tried that, but it solved the problem. Thanks for the help, and thanks for sbt-jib. I'll try coming up with a PR for a multi-project example.

**Comment by schmitch** [comment] 2023-03-30 14:19
the problem is that sbt-jib now uses autoproject, thus you need to disable the jib plugin in some subprojects via:

```
val flyway = (project in file("src/flyway"))
  .settings(commonSettings)
  .settings(ProjectDependencies.flyway)
  .disablePlugins(JibPlugin)
```

**Comment by sideeffffect** [comment] 2023-05-31 23:37
I'll close this issue for now. But feel free to reopen @steven-barnes if you have further questions.

**Closed by sideeffffect** 2023-05-31 23:37 UTC
